name: farGan-sota
channels:
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - Markdown==3.6
    - PyQt5==5.15.11
    - PyYAML==6.0.1
    - Pygments==2.18.0
    - Werkzeug==3.0.3
    - absl-py==2.1.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - cachetools==5.3.3
    - certifi==2024.2.2
    - chardet==5.2.0
    - charset-normalizer==3.3.2
    - cloudpickle==3.0.0
    - contourpy==1.2.0
    - cycler==0.12.1
    - decorator==5.1.1
    - diffusers==0.33.1
    - drjit==0.4.6
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - ffmpeg==1.4
    - flatbuffers==24.3.25
    - fonttools==4.49.0
    - frozenlist==1.4.1
    - fvcore==0.1.5.post20221221
    - gast==0.6.0
    - google-auth==2.30.0
    - google-auth-oauthlib==1.2.0
    - google-pasta==0.2.0
    - grpcio==1.64.1
    - h5py==3.11.0
    - hydra-core==1.3.2
    - idna==3.6
    - importlib-resources==6.1.1
    - importlib_metadata==8.0.0
    - iniconfig==2.0.0
    - iopath==0.1.10
    - ipydatawidgets==4.3.2
    - ipython==8.18.1
    - ipywidgets==8.0.5
    - jedi==0.19.1
    - jupyterlab-widgets==3.0.5
    - keras==2.15.0
    - kiwisolver==1.4.5
    - libclang==18.1.1
    - librosa==0.11.0
    - lightning-utilities==0.11.2
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.7
    - mitsuba==3.5.2
    - ml-dtypes==0.3.2
    - multidict==6.0.5
    - numpy==1.26.4
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - opt-einsum==3.3.0
    - pandas==2.2.0
    - parso==0.8.4
    - pesq==0.0.4
    - pexpect==4.9.0
    - pillow==10.2.0
    - pluggy==1.4.0
    - portalocker==2.8.2
    - prompt_toolkit==3.0.47
    - protobuf==4.25.3
    - psutil==6.1.0
    - pure-eval==0.2.2
    - pyasn1==0.6.0
    - pyasn1_modules==0.4.0
    - pyparsing==3.1.1
    - pystoi==0.4.1
    - pytest==8.0.1
    - python-dateutil==2.8.2
    - pythreejs==2.4.2
    - pytorch-lightning==2.2.5
    - pytz==2024.1
    - regex==2024.11.6
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - safetensors==0.4.5
    - scipy==1.13.1
    - seaborn==0.13.2
    - sionna==0.18.0
    - sounddevice==0.5.2
    - soundfile==0.13.1
    - stack-data==0.6.3
    - statsmodels==0.14.5
    - submitit==1.5.1
    - tabulate==0.9.0
    - taming-transformers==0.0.1
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorboardX==2.6.2.2
    - tensorflow==2.15.1
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.37.0
    - termcolor==2.4.0
    - thop==0.1.1-2209072238
    - tomli==2.0.1
    - torch==2.7.1+cu118
    - torch-geometric==2.6.1
    - torch-operation-counter==0.3.4
    - torchaudio==2.7.1+cu118
    - torchmetrics==1.4.0.post0
    - tqdm==4.66.2
    - traitlets==5.14.3
    - traittypes==0.2.1
    - transformers==4.56.2
    - tzdata==2024.1
    - urllib3==2.2.1
    - wandb==0.21.4
    - wcwidth==0.2.13
    - wheel==0.41.2
    - widgetsnbextension==4.0.11
    - wrapt==1.14.1
    - yacs==0.1.8
    - yarl==1.9.4
    - zipp==3.17.0

